//
//  TaskEditView.swift
//  Sentinel
//
//  Created by Sentinel on 2025-10-24.
//

import SwiftUI

struct TaskEditView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var task: MitigationTask
    let userId: String
    let onSave: (MitigationTask) -> Void

    init(task: MitigationTask? = nil, userId: String, onSave: @escaping (MitigationTask) -> Void) {
        self.userId = userId
        self.onSave = onSave
        _task = State(initialValue: task ?? MitigationTask(
            title: "",
            description: "",
            priority: .medium,
            category: .maintenance,
            status: .notStarted,
            isAIGenerated: false,
            userId: userId,
            notes: "",
            createdAt: Date(),
            updatedAt: Date()
        ))
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Basic Information") {
                    TextField("Task Title", text: $task.title)
                        .font(.headline)

                    TextField("Description", text: $task.description, axis: .vertical)
                        .lineLimit(3...6)
                }

                Section("Details") {
                    Picker("Priority", selection: $task.priority) {
                        ForEach(MitigationTask.Priority.allCases, id: \.self) { priority in
                            HStack {
                                Circle()
                                    .fill(priorityColor(for: priority))
                                    .frame(width: 12, height: 12)
                                Text(priority.rawValue)
                            }
                            .tag(priority)
                        }
                    }

                    Picker("Category", selection: $task.category) {
                        ForEach(MitigationTask.Category.allCases, id: \.self) { category in
                            Text(category.rawValue).tag(category)
                        }
                    }

                    Picker("Status", selection: $task.status) {
                        ForEach(MitigationTask.TaskStatus.allCases, id: \.self) { status in
                            Label(status.rawValue, systemImage: status.icon).tag(status)
                        }
                    }
                }

                Section("Timeline") {
                    DatePicker(
                        "Due Date",
                        selection: Binding(
                            get: { task.dueDate ?? Date() },
                            set: { task.dueDate = $0 }
                        ),
                        displayedComponents: .date
                    )

                    Toggle("Set Due Date", isOn: Binding(
                        get: { task.dueDate != nil },
                        set: { if $0 { task.dueDate = Date() } else { task.dueDate = nil } }
                    ))
                }

                Section("Estimates") {
                    HStack {
                        Text("Estimated Cost")
                        Spacer()
                        TextField("Amount", value: Binding(
                            get: { task.estimatedCost ?? 0 },
                            set: { task.estimatedCost = $0 > 0 ? $0 : nil }
                        ), format: .currency(code: "USD"))
                        .keyboardType(.decimalPad)
                        .multilineTextAlignment(.trailing)
                        .frame(width: 120)
                    }

                    TextField("Estimated Time", text: Binding(
                        get: { task.estimatedTime ?? "" },
                        set: { task.estimatedTime = $0.isEmpty ? nil : $0 }
                    ))
                    .placeholder(when: task.estimatedTime?.isEmpty ?? true) {
                        Text("e.g., 2-3 hours").foregroundColor(.secondary)
                    }
                }

                Section("Additional Notes") {
                    TextField("Notes", text: $task.notes, axis: .vertical)
                        .lineLimit(4...8)
                }

                if task.isAIGenerated {
                    Section {
                        Label("This task was generated by AI", systemImage: "sparkles")
                            .font(.caption)
                            .foregroundColor(.blue)
                    }
                }
            }
            .navigationTitle(task.id == nil ? "New Task" : "Edit Task")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        task.updatedAt = Date()
                        onSave(task)
                        dismiss()
                    }
                    .disabled(task.title.isEmpty)
                }
            }
        }
    }

    private func priorityColor(for priority: MitigationTask.Priority) -> Color {
        switch priority {
        case .critical: return .red
        case .high: return .orange
        case .medium: return .yellow
        case .low: return .green
        }
    }
}

// MARK: - View Extension for Placeholder

extension View {
    func placeholder<Content: View>(
        when shouldShow: Bool,
        alignment: Alignment = .leading,
        @ViewBuilder placeholder: () -> Content
    ) -> some View {
        ZStack(alignment: alignment) {
            placeholder().opacity(shouldShow ? 1 : 0)
            self
        }
    }
}

#Preview {
    TaskEditView(userId: "preview-user") { _ in }
}
